image: node

eslint:
  tags:
    - docker
  stage: build_shop
  script:
    - cd ./onlineshop/source/server/
    - npm ci
    - npm run lint
    - cd ../../
    - cd ./onlineshop/source/client/
    - npm ci
    - npm run lint
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - onlineshop/**/*
